config:
  cwd: './external'
  build_dir: './build'
  build_env:
    CC: 'gcc-14'
    CXX: 'g++-14'

product:
  name: "dawn-sim-oot-user-shell-yaml"
  cores:
    core0:
      name: 'main'
      device: 'sim'
      defconfig: '../../examples/out-of-tree-demo/boards/sim/sim/sim/configs/nsh_user_shell_yaml'
      dcmake:
        CMAKE_SUPPRESS_DEVELOPER_WARNINGS: "ON"
