config:
  cwd: './external'
  build_dir: './build'
  build_env:
    CC: 'gcc-14'
    CXX: 'g++-14'

product:
  name: "dawn-sim-dynamic-desc"
  cores:
    core0:
      name: 'main'
      device: 'sim'
      defconfig: '../../boards/sim/sim/sim/configs/dynamic_desc'
      dcmake:
        CMAKE_SUPPRESS_DEVELOPER_WARNINGS: "ON"
