config:
  cwd: './external'
  build_dir: './build-usensor-can'
  build_env:
    CC: 'gcc-14'
    CXX: 'g++-14'

product:
  name: "dawn-sim-usensor-can"
  cores:
    core0:
      name: 'main'
      device: 'sim'
      defconfig: '../../boards/sim/sim/sim/configs/nsh_usensor_can'
      dcmake:
        CMAKE_SUPPRESS_DEVELOPER_WARNINGS: "ON"
